### ISSUE TITLE
Please reconsider splitting nanoc

### ISSUE THREAD

**Issue by minad** [nanoc-4/nanoc-core#1]
At first thank you for nanoc! It is a great tool for static websites.

 I have seen that you are working on nanoc4 which seems to be split in components. This will make it much more heavy in the     sense that you have to install a lot of gems. I don't see much purpose in doing this splitting. So what I would suggest is mostly keeping the current structure. Nanoc is not such a large project   (I mean it is called "nanoc") that this splitting makes sense. The only result will be that you have a lot of very small gems.
For example if I take a look at https://github.com/nanoc/nanoc-slim/blob/master/lib/nanoc/slim/filter.rb, I see a very small class in its own gem, which isn't somehow worth it. If you would have   it included in the nanoc gem you wouldn't loose anything (assuming that it is somehow autoloaded). The approach to support plugins is good but I would prefer to have most of the batteries included in one single "nanoc" gem.

Advantages of splitting:
* Possibility to separately release the plugins (But this might result in problems with the versions)
* Separate maintainers per plugin, makes sense for large plugins
    - However you can still do that for something like "nanoc-blog", but don't do it for small things like "nanoc-slim" 
* User can select only what he wants to have (Not really an advantage when we have autoloading)
* More enterprisy

Disadvantages of splitting:
* Much more maintainance effort for you, releasing all the separate gems
   - This seems to be especially important since you seem to be the only one really working a lot on this project
   - I think this is the most important point since I think that this change will considerably slow down the progress of the project when you spend more time on splitting/gem maintaining than        features.
* A user who just wants to start quickly has to install the "nanoc-powerpack", which will pull in all template engines because of the dependencies
   - The current behaviour is much nicer. Install "nanoc" and "slim" and get "nanoc" with "slim" support.
* A lot of small gems per class, "clutter". More difficult to maintain, more git repositories...
* More difficult to create packages for distributions

So I would ask you kindly to reconsider. Please tell me what you think!

**Comment by denisdefreyne** [comment]
The new approach to nanoc 4 does not involve splitting it up. This might still happen in the future, but before that happens, I’ll collect feedback and solutions to the problem mentioned in this thread.
